Add description for JudgementHitBurst and ComboDisplay BumpTime and BumpY
Quaver/Quaver.Wiki pull request #200
Opened 2024-08-05 11:20 UTC by WilliamQiufeng

2024-08-05 11:51 UTC, Warp9000 requested changes

2024-08-05 11:51 UTC, Warp9000 commented on en-US/skins/skin.ini.md
we usually realign the tables when adding new stuff thats longer

2024-08-05 12:30 UTC, WilliamQiufeng commented on en-US/skins/skin.ini.md
Fixed

2024-08-06 09:37 UTC, Warp9000 approved these changes

2024-08-06 09:37 UTC, merged